In [1]:
import pandas as pd
import numpy as np
import joblib

In [2]:
model = joblib.load("../models/best_model.pkl")

X_test = joblib.load("../models/X_test.pkl")

y_test = joblib.load("../models/y_test.pkl")

In [3]:
fraud_probability = model.predict_proba(X_test)[:, 1]

predictions = model.predict(X_test)

In [4]:
risk_df = X_test.copy()

risk_df["Actual"] = y_test.values

risk_df["Prediction"] = predictions

risk_df["Fraud_Probability"] = fraud_probability

In [5]:
def assign_risk(prob):

    if prob < 0.20:
        return "Low"

    elif prob < 0.50:
        return "Medium"

    elif prob < 0.80:
        return "High"

    else:
        return "Critical"

In [6]:
risk_df["Risk_Level"] = risk_df["Fraud_Probability"].apply(assign_risk)

risk_df.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,AboveGlobalMean,CardProductFreq,AddrProductFreq,EmailDeviceFreq,NormalizedAmount,NormalizedDistance,Actual,Prediction,Fraud_Probability,Risk_Level
316078,3303078.0,7864752.0,107.950,4,7585.0,553.0,150.0,3,226.0,1,...,0,3256,35530,26799,-0.113217,-0.138579,0,0,0.004689,Low
116888,3103888.0,2260318.0,37.021,0,3154.0,408.0,185.0,2,224.0,2,...,0,4613,65124,33377,-0.409789,-0.183967,0,0,0.011497,Low
410211,3397211.0,10361225.0,59.000,4,10057.0,225.0,150.0,2,224.0,2,...,0,2951,11958,295954,-0.317889,-0.216977,0,0,0.009057,Low
251027,3238027.0,5974846.0,57.950,4,6207.0,355.0,150.0,3,166.0,2,...,0,266,8958,295954,-0.322279,-0.183967,0,0,0.001912,Low
191265,3178265.0,4296816.0,107.950,4,11207.0,361.0,150.0,3,226.0,2,...,0,3283,37520,26799,-0.113217,-0.216977,0,0,0.003644,Low

In [7]:
def recommend_action(level):

    if level == "Low":
        return "Approve"

    elif level == "Medium":
        return "Manual Review"

    elif level == "High":
        return "Hold Transaction"

    else:
        return "Block Transaction"

In [8]:
risk_df["Recommended_Action"] = risk_df["Risk_Level"].apply(
    recommend_action
)

risk_df.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,CardProductFreq,AddrProductFreq,EmailDeviceFreq,NormalizedAmount,NormalizedDistance,Actual,Prediction,Fraud_Probability,Risk_Level,Recommended_Action
316078,3303078.0,7864752.0,107.950,4,7585.0,553.0,150.0,3,226.0,1,...,3256,35530,26799,-0.113217,-0.138579,0,0,0.004689,Low,Approve
116888,3103888.0,2260318.0,37.021,0,3154.0,408.0,185.0,2,224.0,2,...,4613,65124,33377,-0.409789,-0.183967,0,0,0.011497,Low,Approve
410211,3397211.0,10361225.0,59.000,4,10057.0,225.0,150.0,2,224.0,2,...,2951,11958,295954,-0.317889,-0.216977,0,0,0.009057,Low,Approve
251027,3238027.0,5974846.0,57.950,4,6207.0,355.0,150.0,3,166.0,2,...,266,8958,295954,-0.322279,-0.183967,0,0,0.001912,Low,Approve
191265,3178265.0,4296816.0,107.950,4,11207.0,361.0,150.0,3,226.0,2,...,3283,37520,26799,-0.113217,-0.216977,0,0,0.003644,Low,Approve

In [9]:
risk_df.sort_values(
    by="Fraud_Probability",
    ascending=False
).head(20)

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,CardProductFreq,AddrProductFreq,EmailDeviceFreq,NormalizedAmount,NormalizedDistance,Actual,Prediction,Fraud_Probability,Risk_Level,Recommended_Action
34823,3021823.0,855296.0,300.000,1,4141.0,404.0,150.0,2,102.0,1,...,73,460,26857,0.689794,-0.183967,1,1,0.998881,Critical,Block Transaction
132009,3119009.0,2624775.0,300.000,2,7381.0,583.0,150.0,2,102.0,1,...,56,1898,26857,0.689794,-0.183967,1,1,0.998574,Critical,Block Transaction
401902,3388902.0,10129098.0,29.183,0,9917.0,142.0,185.0,3,138.0,2,...,919,65124,26857,-0.442562,-0.183967,1,1,0.998571,Critical,Block Transaction
176475,3163475.0,3822904.0,150.000,1,1306.0,399.0,150.0,0,236.0,1,...,5,1062,26857,0.062605,-0.183967,1,1,0.998521,Critical,Block Transaction
176286,3163286.0,3812152.0,250.000,2,4141.0,404.0,150.0,2,102.0,1,...,106,1898,26857,0.480731,-0.183967,1,1,0.998378,Critical,Block Transaction
179829,3166829.0,3955019.0,200.000,2,4141.0,404.0,150.0,2,102.0,1,...,106,1446,26857,0.271668,-0.183967,1,1,0.998354,Critical,Block Transaction
372330,3359330.0,9254403.0,350.000,2,10486.0,514.0,150.0,2,219.0,1,...,710,1434,26857,0.898857,-0.183967,1,1,0.998180,Critical,Block Transaction
24025,3011025.0,607996.0,200.000,2,11162.0,346.0,150.0,2,224.0,2,...,32,6069,26857,0.271668,-0.183967,1,1,0.998130,Critical,Block Transaction
273841,3260841.0,6644488.0,275.000,2,5313.0,225.0,150.0,2,224.0,2,...,1,3332,26857,0.585262,-0.183967,1,1,0.998079,Critical,Block Transaction
240733,3227733.0,5691368.0,350.000,2,7508.0,321.0,150.0,3,226.0,2,...,85,6069,26857,0.898857,-0.183967,1,1,0.997969,Critical,Block Transaction
257189,3244189.0,6165623.0,400.000,2,13171.0,555.0,150.0,3,226.0,1,...,1,1950,26857,1.107920,-0.183967,1,1,0.997800,Critical,Block Transaction
198764,3185764.0,4491074.0,200.000,2,1675.0,174.0,150.0,3,226.0,2,...,73,3332,295954,0.271668,-0.183967,1,1,0.997791,Critical,Block Transaction
379569,3366569.0,9495920.0,500.000,2,3682.0,264.0,150.0,3,162.0,1,...,323,595,26857,1.526045,-0.183967,1,1,0.997786,Critical,Block Transaction
422591,3409591.0,10699687.0,87.302,0,9026.0,545.0,185.0,3,137.0,1,...,2075,65124,4078,-0.199551,-0.183967,1,1,0.997601,Critical,Block Transaction
24068,3011068.0,608725.0,200.000,2,11162.0,346.0,150.0,2,224.0,2,...,32,595,26857,0.271668,-0.183967,1,1,0.997565,Critical,Block Transaction
198766,3185766.0,4491082.0,200.000,2,1675.0,174.0,150.0,3,226.0,2,...,73,3332,295954,0.271668,-0.183967,1,1,0.997429,Critical,Block Transaction
571031,3558031.0,15170677.0,100.000,2,12883.0,404.0,150.0,3,226.0,1,...,19,1950,26857,-0.146458,-0.183967,1,1,0.997360,Critical,Block Transaction
431591,3418591.0,10895378.0,86.318,0,9633.0,130.0,185.0,3,138.0,2,...,4158,65124,295954,-0.203666,-0.183967,1,1,0.997310,Critical,Block Transaction
160519,3147519.0,3372548.0,200.000,2,4208.0,490.0,150.0,3,195.0,2,...,22,640,5156,0.271668,-0.183967,1,1,0.997306,Critical,Block Transaction
315634,3302634.0,7857631.0,200.000,2,3682.0,264.0,150.0,3,162.0,1,...,323,1431,5156,0.271668,-0.183967,1,1,0.997234,Critical,Block Transaction

In [10]:
risk_df["Risk_Level"].value_counts()

Risk_Level
Low         114497
Critical      1597
Medium        1316
High           698
Name: count, dtype: int64

In [11]:
risk_df["Risk_Level"].value_counts(normalize=True) * 100

Risk_Level
Low         96.942629
Critical     1.352152
Medium       1.114234
High         0.590985
Name: proportion, dtype: float64

In [12]:
risk_df["Fraud_Probability"].describe()

count    118108.000000
mean          0.033908
std           0.123483
min           0.000075
25%           0.003245
50%           0.007051
75%           0.015809
max           0.998881
Name: Fraud_Probability, dtype: float64

In [13]:
pd.crosstab(

    risk_df["Risk_Level"],

    risk_df["Actual"]

)

Actual           0     1
Risk_Level
Critical        40  1557
High            99   599
Low         113193  1304
Medium         643   673

In [14]:
critical_transactions = risk_df[
    risk_df["Risk_Level"] == "Critical"
]

critical_transactions.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,CardProductFreq,AddrProductFreq,EmailDeviceFreq,NormalizedAmount,NormalizedDistance,Actual,Prediction,Fraud_Probability,Risk_Level,Recommended_Action
72645,3059645.0,1621689.0,11.427,0,16746.0,500.0,185.0,2,102.0,1,...,291,65124,26857,-0.516804,-0.183967,1,1,0.889296,Critical,Block Transaction
153357,3140357.0,3178127.0,10.960,0,9917.0,142.0,185.0,3,138.0,2,...,919,65124,33377,-0.518757,-0.183967,1,1,0.966086,Critical,Block Transaction
401769,3388769.0,10124831.0,58.366,0,9917.0,142.0,185.0,3,138.0,2,...,919,65124,26857,-0.320540,-0.183967,1,1,0.965102,Critical,Block Transaction
343112,3330112.0,8457942.0,31.660,0,2675.0,555.0,185.0,3,137.0,1,...,10,65124,295954,-0.432205,-0.183967,1,1,0.965880,Critical,Block Transaction
469909,3456909.0,12114934.0,13.034,0,9633.0,130.0,185.0,3,138.0,2,...,4158,65124,26857,-0.510085,-0.183967,1,1,0.966282,Critical,Block Transaction

In [15]:
risk_df.to_csv(
    "../data/processed/risk_scored_transactions.csv",
    index=False
)

print("Risk scoring completed successfully.")

Risk scoring completed successfully.

In [16]:
risk_df["Confidence"] = np.where(

    risk_df["Prediction"] == 1,

    risk_df["Fraud_Probability"],

    1 - risk_df["Fraud_Probability"]

)

In [17]:
def confidence_level(conf):

    if conf >= 0.95:
        return "Very High"

    elif conf >= 0.80:
        return "High"

    elif conf >= 0.60:
        return "Medium"

    else:
        return "Low"

In [18]:
risk_df["Confidence_Level"] = risk_df["Confidence"].apply(
    confidence_level
)

risk_df.head()

,TransactionID,TransactionDT,TransactionAmt,ProductCD,card1,card2,card3,card4,card5,card6,...,EmailDeviceFreq,NormalizedAmount,NormalizedDistance,Actual,Prediction,Fraud_Probability,Risk_Level,Recommended_Action,Confidence,Confidence_Level
316078,3303078.0,7864752.0,107.950,4,7585.0,553.0,150.0,3,226.0,1,...,26799,-0.113217,-0.138579,0,0,0.004689,Low,Approve,0.995311,Very High
116888,3103888.0,2260318.0,37.021,0,3154.0,408.0,185.0,2,224.0,2,...,33377,-0.409789,-0.183967,0,0,0.011497,Low,Approve,0.988503,Very High
410211,3397211.0,10361225.0,59.000,4,10057.0,225.0,150.0,2,224.0,2,...,295954,-0.317889,-0.216977,0,0,0.009057,Low,Approve,0.990943,Very High
251027,3238027.0,5974846.0,57.950,4,6207.0,355.0,150.0,3,166.0,2,...,295954,-0.322279,-0.183967,0,0,0.001912,Low,Approve,0.998088,Very High
191265,3178265.0,4296816.0,107.950,4,11207.0,361.0,150.0,3,226.0,2,...,26799,-0.113217,-0.216977,0,0,0.003644,Low,Approve,0.996356,Very High

In [19]:
risk_df[[
    "Fraud_Probability",
    "Risk_Level",
    "Confidence",
    "Confidence_Level",
    "Recommended_Action"
]].head(20)

,Fraud_Probability,Risk_Level,Confidence,Confidence_Level,Recommended_Action
316078,0.004689,Low,0.995311,Very High,Approve
116888,0.011497,Low,0.988503,Very High,Approve
410211,0.009057,Low,0.990943,Very High,Approve
251027,0.001912,Low,0.998088,Very High,Approve
191265,0.003644,Low,0.996356,Very High,Approve
17694,0.022744,Low,0.977256,Very High,Approve
431807,0.004468,Low,0.995532,Very High,Approve
368899,0.001192,Low,0.998808,Very High,Approve
390704,0.002207,Low,0.997793,Very High,Approve
140623,0.007531,Low,0.992469,Very High,Approve
325130,0.001681,Low,0.998319,Very High,Approve
538499,0.050116,Low,0.949884,High,Approve
375228,0.017460,Low,0.982540,Very High,Approve
163935,0.013029,Low,0.986971,Very High,Approve
407237,0.003969,Low,0.996031,Very High,Approve
263918,0.020025,Low,0.979975,Very High,Approve
549489,0.005900,Low,0.994100,Very High,Approve
533868,0.009224,Low,0.990776,Very High,Approve
175659,0.009550,Low,0.990450,Very High,Approve
102772,0.025865,Low,0.974135,Very High,Approve

In [20]:
risk_df.to_csv(
    "../data/processed/fraud_risk_analysis.csv",
    index=False
)

print("Final fraud risk analysis dataset saved successfully!")

Final fraud risk analysis dataset saved successfully!